
version: '3.1'

services:

  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80

  db:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - 3333:80
    environment:
      - PMA_ARBITRARY=1
